# Generated by Django 4.2.11 on 2024-04-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appOne", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="appOne.equipment",
            ),
        ),
    ]
